### PR TITLE
Filter dropdownlist

### PR DESCRIPTION
**Pull request by nxrara**
Added in search filters for 
- search bar for names, distance, location
- filter distance (<= 2km, 2km to 5km, >5km) => added in distance in each trail card within index page
- filter difficulties level (easy, intermediate, difficult)
- filter duration (<45mins, 45min to 90 min, >90min)
- the filter selections in filters and search in search bar will be retained once submitted, before clear filter
- clear filter buttons
- If no results found, there will be prompt - No trail found
- no merge conflicts as of now
- styled buttons

### CODE REVIEW

**Comment by barbayjuliette** [comment]
- Can you put colors to the buttons? Same styling as the login forms.
- Once I get the results, the applied filter disappears in the bar, which makes it confusing : After clicking on search, the search term should still appear in the bar, until I click clear filters.
- AFter each criteria there is a star that says it is required, but it is not: take it out.
- If no results found, say something like: Sorry, no trails found/matching your criteria
- Make the search fields responsive

**Review by barbayjuliette — CHANGES_REQUESTED** [review]
See comments

**Review by lxingern — APPROVED** [review]
Ok to merge, looks good. Just change 'clear search' to 'clear' or 'reset'. Thanks!

**Comment by nxrara** [comment]
@barbayjuliette addressed ur comments thus ready for final review, thankss

**Comment by barbayjuliette** [comment]
Can you add for all filters the option "All". 
So that if I am using several filters, I wanna keep them all except one, I can do it

**Review by barbayjuliette — APPROVED** [review]
Okay, but later change the responsiveness 
- Make fields smaller
- Take less vertical space
- Margin right and left

**Review by lxingern — APPROVED** [review]
Ok to merge

**Pull request merged**
