### PR TITLE
Show page for trail

### PR DESCRIPTION
**Pull request by lxingern**
- Added a Google map for directions (clicking on the location - the link with the location pin - will also bring you down to the map)
- Redesigned the show page as discussed
- Users will now see the first 3 reviews in the 'Ratings & Reviews' section and can click on the link at the bottom to see all reviews in a pop up modal
- Ratings and the number of stars are now dynamic - added a method to the Trail model to calculate the average rating from reviews => We might want to consider adding a rating column to the Trail model instead.

### CODE REVIEW

**Comment by lxingern** [comment]
[Redesign trail show page](https://trello.com/c/ezrriFZm/50-redesign-trail-show-page)

**Comment by f-Xiaoxi** [comment]
image

- The create trip button does not align well with the other titles. Maybe make it longer in width and shorten the height.
- Is there a link for the review?
- Maybe shorten the divider line for each section? 
- Text can be slightly bigger

**Comment by f-Xiaoxi** [comment]
The line above getting there should also be the same length? But otherwise looks fine

**Comment by lxingern** [comment]
Oops sorry... have changed it to be the same.

**Review by f-Xiaoxi — APPROVED** [review]
Looks good

**Pull request merged**
