### PR TITLE
linked cloudinary

### PR DESCRIPTION
**Pull request by f-Xiaoxi**
Added wloudinary

### CODE REVIEW

**Comment by lxingern** [comment]
Can you set the relationship on the Trail model? I.e. 'has_many_attached :photos'

**Comment by barbayjuliette** [comment]
@f-Xiaoxi Can you update the seed and add 2/3 pictures to each trail ?

**Comment by f-Xiaoxi** [comment]
added has_many_photos

**Review by lxingern — APPROVED** [review]
Ok to merge, I will work on the seeds in another branch.

**Pull request merged**
