### PR TITLE
Index page design

### PR DESCRIPTION
**Pull request by barbayjuliette**
Created the grid of cards. 
- Which font should I add? 
- Will need to add link to bookmark and index in next stories
- Once we have the reviews table, we can order the index page by rating and color the stars accordingly
- I still need to adapt the card in case the title is too long.
- Changed color of the stars to make it more visible (should reflect on the show page as well)
- For duration: I was thinking we should have duration_hours and durations minutes in the database in order to be able to display the time correctly. Because a float doesn't make sense here. After that I can adapt the duration on card
- Which styling do you want me to add to the cards? Any colors? More margin? I added a color variable as a suggestion in application.scss
- Grid is responsive.
- Will make the pictures as carousel when pictures added

### CODE REVIEW

**Review by lxingern — APPROVED** [review]
Ok to merge - styling can come later.

For duration, what I did for the show page was to divide the duration by 60 so that it is displayed in hours (e.g. 4.6 hours) instead. If we want to go with something like 4h36m, I think we can do the conversion from minutes via a method in the model instead of having 2 columns for hours and minutes in the schema.

**Comment by barbayjuliette** [comment]
- 3 cards per page
-  Changed the responsiveness
-  Changed grid gap
- added border radius to cards

When hover card : Couldn't find how to zoom without making the picture bigger. Still to do. I could also add different opacity to image when hover image, or add green border to the card when hover

We still have to choose color of navbar and page, so that I can adapt the background color.

**Comment by f-Xiaoxi** [comment]
I think white for nav bar is fine. Added a faint shadow to it.
Can add more changes to it if there is time but looks ok for now.

**Comment by barbayjuliette** [comment]
@lxingern For the time: 
You delete by 60, but then 4.6 hours means what ? 
4 hours, 60 minutes? 
4 hours + 0.6 hour ? 
If the division gives you 4.9 hour, then what does it mean ? 
I feel that it is not clear that way
When the hour is displayed that way, you can write 1.5 hour, but 1.7 hour or 1.2 hour is very confusing

Right now, in the DB, we have a number between 10 and 500.
We could convert that directly to minutes and then to hours and minutes. 
Wouldn't it be easier to have it in the DB ?

**Pull request merged**
