### PR TITLE
Styled search bar

### PR DESCRIPTION
**Pull request by nxrara**
-styled search bar according to current page design

### CODE REVIEW

**Review by lxingern — CHANGES_REQUESTED** [review]
Some suggestions:
- Make the text field longer
- Add a link to clear the search
- Maybe put the search bar under the header "Find your next hike"?

**Comment by nxrara** [comment]
@lxingern branch has been edited to address all comments, thanks

**Review by lxingern — APPROVED** [review]
Ok to merge.

Actually I was thinking that the clear search button can be less prominent than the search button. Can be styled differently or can be just plain text with an underline (i.e. the default link styling). But we can make this change later on. Thanks!

**Comment by nxrara** [comment]
@lxingern i will make the change (styling of clear button) on my filter branch, thank youu

**Pull request merged**
