### PR TITLE
Date select form on show page for trails

### PR DESCRIPTION
**Pull request by lxingern**
- Added a pop up form for user to enter the date/time trip when they click on the 'add' button (the plus sign) in the trail show page
- Added date validation for presence back into the Trip model
- Added a new validation to the Trip model where the date must be in the future
- Form in show page will show an error message, will not be submitted if user enters a date in the past

I tried to find a package/gem to display a nice calendar which the user can click on to select the date... but couldn't find any updated ones :( Maybe I'll try again next time

Remember to run 'yarn build --watch' when you test this as I used Stimulus for the form.

### CODE REVIEW

**Comment by barbayjuliette** [comment]
[Add form to select date in trail show page](https://trello.com/c/frwLZoWS/18-add-form-to-select-date-in-trail-show-page)

**Comment by barbayjuliette** [comment]
- Style form
- The "plus" button is on the right, I think it would make more sense if it was next to the bookmark button. Here, it is kind of "hidden"
- If I create a trip for today, but earlier in the day, it works. Should also have an error
- Would be way better to have a calendar. Maybe you could ask the team who did the meetup project which gem they used last time
-  Would be better for the user, if for the minutes can only choose multiples of 15 (or 5). Now, has to scroll a lot. ANd who would want to put 13.06?
-

**Comment by barbayjuliette** [comment]
Once the trip is created: show plus AND minus/delete
--> User can plan a second trip there already
--> User can delete this from his trips

**Review by barbayjuliette — CHANGES_REQUESTED** [review]
Maybe do changes before we push.

**Comment by lxingern** [comment]
- Should throw an error if you select a time earlier in the day now.
- Minutes are in multiples of 15

I think we can relook at the styling tomorrow when we have a better idea of what our overall design scheme is. I was planning to redo the button to make it more prominent - I shifted it out to the right so that it wouldn't be buried among the other buttons, since creating a trip is the main thing that we want the user to do on the page. 

I couldn't find a way to make the date field change depending on the month the user selects. This problem would be resolved when we find out a way to implement a calendar select. Otherwise we can do another validation to check for invalid dates.

**Comment by lxingern** [comment]
Implemented 'flatpickr' package to display calendar for the user to select the date and time.

**Comment by barbayjuliette** [comment]
Looks good. We can merge already. 
If I choose a date / time in the past, I get a message. Okay. But I shouldn't be able to choose a date in the past. Right now, I can change the year to 2019 for example, shouldn't be possible (only from current year). When opening the calendar in current month, the past dates should not be selectable.

**Comment by barbayjuliette** [comment]
Also, where do we want to redirect after we created the trip? Right now, it is the trips index. 
--> I would say either stay on the same page or the trip show view

**Review by barbayjuliette — APPROVED** [review]
Ready to merge. Just a few comments for later / suggestions

**Pull request merged**
