### PR TITLE
Add picture to past trips

### PR DESCRIPTION
**Pull request by barbayjuliette**
I can upload pictures for my trips. 
When I upload a picture, it is shown directly on the page (ajax)
I can click on each picture and I have a popup.
Each popup is a carousel 

- Still need to add ajax for the carousel.
- carousel is a bit weird, doesn't always work. I don't know why !!
- Make grid responsive? But the whole page not responsive at all yet.

### CODE REVIEW

**Comment by f-Xiaoxi** [comment]
- Carousel doesn't work for me. Do I have to run extra code in the terminal?
- The close(x) button is slightly too close to the edge
- Should the gallery be scrollable? I added 20 photos and the page is really long now.
image

**Comment by barbayjuliette** [comment]
Carousel doesn't work for me. Do I have to run extra code in the terminal?

--> It works, after a while... I will work on it more today

    The close(x) button is slightly too close to the edge
--> Okay, I can change it

    Should the gallery be scrollable? I added 20 photos and the page is really long now.
--> But realistically, would we really add that many pictures? I think we could leave it like this for now, and if I put all the pictures on the trail page, then I would make it scrollable.

**Comment by f-Xiaoxi** [comment]
Ajax working fine. 

- Can you make the 'add pic' button closer to the upload bar?
-Maybe also align upload bar with the title ?

image

**Comment by f-Xiaoxi** [comment]
Not sure why, but when I refreshed the page, the 'close' button is not aligned even though it's aligned before refreshing
image

**Comment by barbayjuliette** [comment]
Ready for review
I changed the style of the form, and the close button of the carousel.
I also added under each trail all the pictures uploaded by users for that trail. 

Still to do: 
- If user adds more than one picture, currently, the ajax of the popup is only for the last one. I have to make it for all.

**Comment by lxingern** [comment]
The position of the 'x' is fine on the trail show page:
image

But still a bit awkward on the trip show page:
image

**Review by lxingern — APPROVED** [review]
Ok to merge, just need to fix the gap between the close button and top of the window after the photos are uploaded.

**Pull request merged**
