### PR TITLE
Replace map in trail show page with route map

### PR DESCRIPTION
**Pull request by lxingern**
Replaced the Getting There section with the map for directions with a Trail Map section that displays the mapbox map with the trail route instead

### CODE REVIEW

**Comment by f-Xiaoxi** [comment]
Looks good. 
The maps for Lower Peirce Reservoir Park and Labrador Park to Harbourfront Walk are not showing up though.

**Comment by lxingern** [comment]
Oops ok, fixed the issue. Lower Peirce will now be Casuarina Road - Bukit Panjang because there's no Lower Peirce trail in All Trails

**Comment by f-Xiaoxi** [comment]
Both maps working fine now

**Review by f-Xiaoxi — APPROVED** [review]
Working fine

**Review by f-Xiaoxi — APPROVED** [review]
Ok

**Pull request merged**
