### PR TITLE
Index page cards

### PR DESCRIPTION
**Pull request by barbayjuliette**
Modified the cards on the index page
Added bookmark on the picture: I had to add a background color and opacity so that if the picture is white, we can still see it.

### CODE REVIEW

**Comment by barbayjuliette** [comment]
I put the cards in a partial to use them in the bookmark index as well

**Comment by f-Xiaoxi** [comment]
image
Black border below image looks weird.

**Comment by barbayjuliette** [comment]
I fixed the black line under the pictures. 
For the title: If the title is too long, it wraps. So I was talking with Ashley about how to do it since I could do like before and only display limited letters if too long. But if I resize window, the width changes, So, more or less space, so it doesn't work. Doesn't work on different browser sizes. So 2 solutions: 
- We keep it like that and we are okay if it wraps.
- We put them on different lines. 
What do you prefer?

**Review by lxingern — APPROVED** [review]
Ok to merge, just one minor comment - the trail name and rating are not aligned horizontally. Can fix this later on.
image

**Pull request merged**
